apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
data:
  mysql-init.sql: |
    CREATE TABLE IF NOT EXISTS Student (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        grade DECIMAL(5,2) NOT NULL
    );