# HPA for Enter Grades App
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: enter-grades-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: enter-grades-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
        type: Utilization
        averageUtilization: 5

# HPA for Show Results App
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: show-results-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: show-results-app
  minReplicas: 1
  maxReplicas: 5
  metrics:

  # TESTING SCALABILTY 
    # - type: Resource
    #   resource:
    #     name: cpu
    #     target:
    #       type: Utilization
    #       averageUtilization: 1

    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80         
          
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 5

